import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docsSidebar: [
    {
      type: "doc",
      id: "overview",
    },
    {
      type: "doc",
      id: "formats",
    },
    {
      type: "doc",
      id: "terms",
    },
    {
      type: "doc",
      id: "license",
    },
    {
      type: "doc",
      id: "quality",
    },
    {
      type: "doc",
      id: "providers",
    },
    {
      type: "doc",
      id: "parameters",
    },
    {
      type: "doc",
      id: "weather-stations",
    },
    {
      type: "doc",
      id: "contribute",
    },
    {
      type: "doc",
      id: "donate",
    },
    {
      type: "doc",
      id: "faq",
    },
  ],
  pythonSidebar: [{ type: "autogenerated", dirName: "python" }],
  dataSidebar: [{ type: "autogenerated", dirName: "data" }],
  apiSidebar: [
    { type: "autogenerated", dirName: "api" },
    {
      type: "link",
      label: "Playground",
      href: "https://rapidapi.com/meteostat/api/meteostat/",
    },
  ],
};

export default sidebars;
